### ISSUE TITLE
EventType names do not match actual events messages names

### ISSUE THREAD

**Issue by n0izn0iz** [berty/weshnet#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package version

v1.10.0

### OS

Other

### Language version and compiler version

go1.20.4

### Bug description

Some event messages names do not match their EventType name
For example the message corresponding to `EventType.AccountContactRequestIncomingReceived` is actually called `AccountContactRequestReceived`

This is annoying for writing generic events decoders (it's useful for dumping payloads for example)

I wrote a little script to find inconsistent event naming

```
❯ npx ts-node packages/scripts/checkWeshnetConsistency.ts
Missing event definition for GroupMemberDeviceAdded
Missing event definition for GroupDeviceChainKeyAdded
Missing event definition for AccountContactRequestOutgoingEnqueued
Missing event definition for AccountContactRequestOutgoingSent
Missing event definition for AccountContactRequestIncomingReceived
Missing event definition for AccountContactRequestIncomingDiscarded
Missing event definition for AccountContactRequestIncomingAccepted
Missing event definition for ContactAliasKeyAdded
Missing event definition for MultiMemberGroupAliasResolverAdded
Missing event definition for MultiMemberGroupInitialMemberAnnounced
Missing event definition for MultiMemberGroupAdminRoleGranted
Missing event definition for GroupMetadataPayloadSent
```

### Current behavior

Some event messages names do not match their EventType name

### Expected behavior

All events messages names do match their EventType name

### Environment

macOS 13.3.1

### Other

Since this is an api breaking change I would recommend fixing this before the api is widely consumed

**Comment by jefft0** [comment]
Hello @n0izn0iz . You have a valid point. I agree that we should make breaking API changes now. I have a question. In general the API call is a "verb" and the resulting event is a "noun". For example the API call `ContactAddAliasKey` causes the event `ContactAliasKeyAdded` . It seems natural that a command to "add" results in an event which says "added". How do you suggest to rename these? Thanks.

**Comment by n0izn0iz** [comment]
> It seems natural that a command to "add" results in an event which says "added". How do you suggest to rename these?
This seems ok, it's not the api call that don't match, it's the event types and messages, in this case, both will be "Added"

I think in the case of `ContactAddAliasKey`, the api call is "ContactAliasKeySend", in the comments, it's stated that `ContactAddAliasKey` is an event
