### ISSUE TITLE
allow friends to relay encrypted messages between mutuals

### ISSUE THREAD

**Issue by jmaris** [berty/weshnet#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature request

Alice, Tom and Bob are friends. Alice wants to send a message to Bob but internet is not available. She meets with tom, who is also friends with bob.

Berty transfers an encrypted copy of Alice's message onto toms phone.

Later, tom meets bob, and Alice's message is transferred from tom's phone to bobs.

### Context

While BLE does allow for localised transmission of messages from one person to another, it doesn't enable long-distance transmission in an internet-less environment. 

Allowing users to store messages and relay them could dramatically increase range in internet-less environments

**Comment by jefft0** [comment]
In Wesh, for security reasons, if Tom is going to act as a relay, then Tom needs to already be in a message group with Alice and Bob. If they are all in the same group, then effectively it's not "Alice sending a message to Bob" but "Alice putting a message in a group where Tom and Bob are members." The Wesh protocol will sync all the users to have the same message list.

**Comment by jefft0** [comment]
Closing as inactive.
